# Common Labels
labels:
  app: "console"
  group: "web"

namespace: egov    

# Ingress Configs
ingress:
  enabled: true
  context: "console"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "console"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/console/"
  readinessProbePath: "/console/"

# Environment Variables for Proxy
env: |
  - name: ELASTICSEARCH_URL
    value: "https://elasticsearch-master.es-cluster:9200/"
  - name: KIBANA_URL
    value: "http://release-name-kibana.es-cluster:5601/"
  - name: PROXY_PORT
    value: "3001"

        
extraVolumes: |
  - name: js-injection
    configMap:
      name: console-js-injection

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
